title: Sean Khomphengchan
url: "https://seankhom.github.io"
baseurl: ""
remote_theme: ankitsultana/researcher@gem
markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/seankhom"
footer_text: "Sean Khomphengchan's Site"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Portfolio"
   link: "portfolio"
 - name: "Coursework"
   link: "coursework"
 - name: "Resume"
   link: "SEANKHOM_RESUME_S2023.pdf"
 - name: "Contact"
   link: "contact"
